### ISSUE TITLE
1.20.4 "java.lang.IllegalArgumentException: UUID id cannot be null"

### ISSUE THREAD

**Issue by DartPower** [notnotnotswipez/TerminatorNPC#4]
On 1.20.4 throws error:
```
[14:26:51 WARN]: [TerminatorNPC] Task #46319 for TerminatorNPC v1.5-SNAPSHOT generated an exception
java.lang.IllegalArgumentException: UUID id cannot be null
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.getPlayer(CraftServer.java:721) ~[purpur-1.20.4.jar:git-Purpur-2110]
        at org.bukkit.Bukkit.getPlayer(Bukkit.java:732) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at me.swipez.terminatornpc.trait.TerminatorTrait.getTarget(TerminatorTrait.java:950) ~[TerminatorNPC-1.5-SNAPSHOT.jar:?]
        at me.swipez.terminatornpc.trait.TerminatorTrait$1.run(TerminatorTrait.java:355) ~[TerminatorNPC-1.5-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2110]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[purpur-1.20.4.jar:git-Purpur-2110]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1666) ~[purpur-1.20.4.jar:git-Purpur-2110]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.4.jar:git-Purpur-2110]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1545) ~[purpur-1.20.4.jar:git-Purpur-2110]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1235) ~[purpur-1.20.4.jar:git-Purpur-2110]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.4.jar:git-Purpur-2110]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by DartPower** [comment]
This message spams in the server's console
